### PR TITLE
 Make dependency version requirements less restrictive

### PR DESCRIPTION
**Pull request by nebolsin**
- [x] Add .ruby-version to .gitignore, because there's no strict dependency on the specific version of Ruby
- [x] Lift up the dependency version restrictions a bit

It would be great if you can release an updated version to Rubygems so that dependant applications can upgrade to `stellar-base 0.14.0`.

/cc @nullstyle

### CODE REVIEW

**Comment by ramontayag** [comment]
I feel the `.ruby-version` is meant mainly for developers of the gem to default to a specific version of Ruby, mainly to avoid inter-version confusion. I find this useful.

In fact, I'm about to make a PR to update it to `2.4.1` 😃

**Comment by ramontayag** [comment]
I do want less resitrictive gem versions though 👍

**Comment by nullstyle** [comment]
LGTM.  I'll look into making a release tomorrow.  thanks!

**Comment by nebolsin** [comment]
@nullstyle Thanks for merging. Are there any blockers for release?

**Comment by nullstyle** [comment]
I just released v0.14.0 of stellar-base and v0.4.0 of stellar-sdk to rubygems @nebolsin.   Sorry about the delay!

**Pull request merged**
